apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-pods
  namespace: home-namespace
subjects:
- kind: ServiceAccount
  name: home-operator
  namespace: home-namespace
roleRef:
  kind: Role
  name: monitoring-role
  apiGroup: rbac.authorization.k8s.io 